import os
# Base directory
BASE_DIR = os.path.abspath(os.path.dirname(__file__))

# Folder options
TEMPLATE_FOLDER = '{:s}/tmp'.format(BASE_DIR)
UPLOAD_FOLDER = '{:s}/uploads'.format(BASE_DIR)

# Secret, e.g. for signing cookies
# TODO: Should be changed
# Currently generated by: http://goo.gl/O4Ogb5
SECRET_KEY = 'MYpqfhw2FMRHODTGUvH7NB6KPcX4N0Q8dS0VbPfU'

# Application salt
# Currently generated by: http://goo.gl/G17KGR
SALT = 'RCrf2IgHdb2gVhjm8S6O0g649dZ2X3f8SFQKZCBpc0hevycJVkiYgImCLvDS'

# TODO: Add database information etc.
PG_DB = {
    'default': {
        'auto_connect': True,
        'database': 'restful',
        'user': 'mys',
        'password': 'SecurePassword',
        'host': 'localhost',
        'port': 5432,
        'connection_factory': None,
        'cursor_factory': None,
        'async': False,
        'autocommit': True
    }  # ,
    # 'content': {
    #        'auto_connect': False,
    #        'database': 'something',
    #        'user': 'new',
    #        'password': 'orOldWhatEver',
    #        'host': 'content.example.com',
    #        'port': 42,
    #        'connection_factory': None,
    #        'cursor_factory': None,
    #        'async': False,
    #        'autocommit': False
    #    }
}
